"""Text cleaning and NLP preprocessing for scraped opinions."""

import re

import contractions
import emoji
import nltk
from bs4 import BeautifulSoup
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

MIN_WORD_COUNT = 10

BOT_PHRASES = [
    "i am a bot",
    "this is an automated",
    "auto-generated",
    "this action was performed automatically",
    "beep boop",
    "generated by",
    "posted automatically",
    "this is a bot",
]

BOT_AUTHOR_PATTERNS = [
    re.compile(r"bot\b", re.IGNORECASE),
    re.compile(r"\.bot$", re.IGNORECASE),
    re.compile(r"automod", re.IGNORECASE),
]


def _ensure_nltk_data():
    for resource in ["punkt_tab", "stopwords", "wordnet"]:
        try:
            nltk.data.find(
                f"tokenizers/{resource}" if "punkt" in resource
                else f"corpora/{resource}"
            )
        except LookupError:
            nltk.download(resource, quiet=True)


class TextCleaner:
    """NLP text preprocessing pipeline."""

    def __init__(self):
        _ensure_nltk_data()
        self._lemmatizer = WordNetLemmatizer()
        self._stop_words = set(stopwords.words("english"))

    def clean(self, text: str, author: str = "") -> tuple[str | None, str]:
        """Returns (cleaned_text, clean_status)."""
        if self._is_bot(text, author):
            return None, "bot"

        cleaned = self._preprocess(text)

        if len(cleaned.split()) < MIN_WORD_COUNT:
            return None, "too_short"

        return cleaned, "cleaned"

    def _preprocess(self, text: str) -> str:
        # 1. Strip HTML
        text = BeautifulSoup(text, "html.parser").get_text(separator=" ")
        # 2. Expand contractions
        text = contractions.fix(text)
        # 3. Convert emojis to text
        text = emoji.demojize(text, delimiters=(" ", " "))
        # 4. Lowercase
        text = text.lower()
        # 5. Remove URLs
        text = re.sub(r"https?://\S+", "", text)
        # 6. Remove numbers
        text = re.sub(r"\d+", "", text)
        # 7. Remove punctuation and special characters
        text = re.sub(r"[^\w\s]", "", text)
        # 8. Normalize whitespace
        text = re.sub(r"\s+", " ", text).strip()
        # 9. Tokenize
        tokens = word_tokenize(text)
        # 10. Remove stop words
        tokens = [t for t in tokens if t not in self._stop_words]
        # 11. Lemmatize
        tokens = [self._lemmatizer.lemmatize(t) for t in tokens]
        return " ".join(tokens)

    @staticmethod
    def _is_bot(text: str, author: str) -> bool:
        text_lower = text.lower()
        for phrase in BOT_PHRASES:
            if phrase in text_lower:
                return True
        for pattern in BOT_AUTHOR_PATTERNS:
            if pattern.search(author):
                return True
        return False
